{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubeupdater.fullname" . }}-node
  namespace: kube-system
  labels:
    {{- include "kubeupdater.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - kubeupdater
  verbs:
  - get
  - watch
{{- end }}
