{{- if and (hasKey .Values "serviceAccount") (.Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-oidc-discovery-provider.serviceAccountName" . }}
  labels:
    {{- include "k8s-oidc-discovery-provider.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
