apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alma-kickstart.fullname" . }}-grub
  labels:
    {{- include "alma-kickstart.labels" . | nindent 4 }}
    component: grub
data:
  "grub.cfg": |
    {{ tpl .Values.grub.config . | nindent 4 }}
