{{- if .Values.gateway.httpsRedirect.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: {{ .Values.magicnamespace.namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ template "namespace.gatewayName" . }}
    namespace: {{ template "namespace.gatewayNamespace" . }}
    sectionName: {{ default "http" .Values.gateway.httpsRedirect.sectionName }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: {{ default 302 .Values.gateway.httpsRedirect.statusCode }}
{{- end }}
