## Append samples you want in your CSV to this file as resources ##
resources:
- miscscripts_v1beta1_tenantnamespace.yaml
- miscscripts_v1beta1_tenantnamespaceflavor.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
